2017-11-09 11:03:43.764 [error] <0.616.0> /home/pampa/pampa_pro/src/pampa_pro_app.erl:9: Error: record amqp_params_direct undefined
/home/pampa/pampa_pro/src/pampa_pro_app.erl:9: Warning: variable 'Connection' is unused
2017-11-09 11:06:28.794 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:06:28.794 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:06:28.795 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239 in context child_terminated
2017-11-09 11:06:28.795 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:06:28.795 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@127.0.0.1.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196788794},{node,'pampa_pro@127.0.0.1'},{user_who_performed_action,none}]],[]},{...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:08:09.505 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:08:09.505 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:08:09.505 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239 in context child_terminated
2017-11-09 11:08:09.506 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:08:09.506 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@127.0.0.1.1.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196889505},{node,'pampa_pro@127.0.0.1'},{user_who_performed_action,none}]],[]},{...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:08:59.869 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:08:59.870 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:08:59.870 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:08:59.870 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:08:59.870 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196939869},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:11:25.878 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:11:25.879 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:11:25.879 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239 in context child_terminated
2017-11-09 11:11:25.879 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:11:25.879 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@VM_0_14_centos.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197085878},{node,pampa_pro@VM_0_14_centos},{user_who_performed_action,none}]],...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:13:25.721 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:13:25.721 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:13:25.721 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239 in context child_terminated
2017-11-09 11:13:25.721 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:13:25.722 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@VM_0_14_centos.1.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197205720},{node,pampa_pro@VM_0_14_centos},{user_who_performed_action,none}]],...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:16:16.750 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:16:16.750 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:16:16.751 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:16:16.751 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:16:16.751 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197376749},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:37:42.115 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:37:42.115 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:37:42.116 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:37:42.116 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:37:42.116 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510198662115},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:38:59.503 [error] <0.669.0>@amqp_connection:start_direct CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: call to undefined function amqp_connection:start_direct() in application_master:init/4 line 134
2017-11-09 11:45:43.226 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:45:43.226 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:45:43.226 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:45:43.226 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:45:43.226 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510199143225},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:54:17.973 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 11:54:17.973 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 11:54:17.974 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 11:54:17.974 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:54:17.974 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:12:54.065 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:12:54.066 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:12:54.066 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:12:54.066 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:12:54.066 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:16:03.279 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:16:03.280 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:16:03.280 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:16:03.280 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:16:03.280 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:21:27.294 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:21:27.294 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:21:27.295 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:21:27.295 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:21:27.295 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:25:08.680 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:25:08.680 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:25:08.681 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:25:08.681 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:25:08.681 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:25:35.341 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:25:35.341 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:25:35.341 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 12:25:35.341 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:25:35.342 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510201535340},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:26:45.862 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:26:45.862 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:26:45.863 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 12:26:45.863 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:26:45.863 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510201605862},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 14:04:12.595 [error] <0.616.0> /home/pampa/pampa_pro/src/ws_handler.erl:1: Error: no module definition
2017-11-09 14:06:03.845 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:1: Error: no module definition
2017-11-09 14:23:43.955 [error] <0.616.0> /home/pampa/pampa_pro/src/ws_handler.erl:16: Warning: variable 'WsId' is unused
/home/pampa/pampa_pro/src/ws_handler.erl:19: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:40: Warning: variable 'MsgerPid' is unused
/home/pampa/pampa_pro/src/ws_handler.erl:42: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:44: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:59: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:65: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:90: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:91: Error: record ws_state undefined
2017-11-09 14:25:56.451 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
2017-11-09 14:26:05.573 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
2017-11-09 14:26:19.757 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
